# Ayu Mirage
set -g status-style "bg=#1f2430,fg=#cbccc6"
set -g window-status-format " #I:#W "
set -g window-status-style "bg=#2d3347,fg=#707a8c"
set -g window-status-current-format " #I:#W "
set -g window-status-current-style "bg=#5ccfe6,fg=#1f2430,bold"
set -g status-left-style "bg=#5ccfe6,fg=#1f2430,bold"
set -g status-right-style "bg=#1f2430,fg=#707a8c"
set -g pane-border-style "fg=#2d3347"
set -g pane-active-border-style "fg=#5ccfe6"
set -g message-style "bg=#2d3347,fg=#cbccc6"
