# Gruvbox
set -g status-style "bg=#282828,fg=#ebdbb2"

set -g window-status-format " #I:#W "
set -g window-status-style "bg=#3c3836,fg=#a89984"

set -g window-status-current-format " #I:#W "
set -g window-status-current-style "bg=#d79921,fg=#1d2021,bold"

set -g status-left-style "bg=#d79921,fg=#1d2021,bold"
set -g status-right-style "bg=#282828,fg=#a89984"

set -g pane-border-style "fg=#3c3836"
set -g pane-active-border-style "fg=#d79921"

set -g message-style "bg=#3c3836,fg=#ebdbb2"
