# Tokyo Night
set -g status-style "bg=#1a1b26,fg=#c0caf5"

set -g window-status-format " #I:#W "
set -g window-status-style "bg=#292e42,fg=#787c99"

set -g window-status-current-format " #I:#W "
set -g window-status-current-style "bg=#7aa2f7,fg=#1a1b26,bold"

set -g status-left-style "bg=#7aa2f7,fg=#1a1b26,bold"
set -g status-right-style "bg=#1a1b26,fg=#787c99"

set -g pane-border-style "fg=#292e42"
set -g pane-active-border-style "fg=#7aa2f7"

set -g message-style "bg=#292e42,fg=#c0caf5"
